version: '3.8'
services:
  mtquizbot-container:
    image: client:0.0.1
    build:
      context: ./QuizBot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/quiz_db_1
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8081,server=y,suspend=n
    networks:
      - postgres
      - redis

  postgres:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: quiz_db_1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
    ports:
      - 5432
    volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres

  redis:
    image: redis:alpine
    container_name: redis
    ports:
     - 6379
    volumes:
      - ./.redisdata:/data
    networks:
      - redis

networks:
    postgres:
        driver: bridge
    redis:
        driver: bridge
